version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80 # Porta usada pelo arquivo default.conf.
      - 8080:8080 # Porta usada pelo arquivo nginx.conf.
      - 8001:8001 # Serviço 1.
      - 8002:8002 # Serviço 2.
      - 8003:8003 # Contém o load-balancer.
    volumes:
      - ./arquivos:/arquivos
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./servicos:/servicos
      - ./logs:/etc/nginx/logs # Esta pasta não existiria no container.
    container_name: nginx
    networks:
      - rede
  php-server: # Nome na rede interna.
    image: php:7-apache
    volumes: 
      - ./php:/var/www/html
    container_name: php # Nome no controle do docker.
    networks:
      - rede

networks:
  rede:
    driver: bridge
    name: rede