version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./arquivos:/arquivos
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    networks:
      - rede

networks:
  rede:
    driver: bridge
    name: rede